import * as XLSX from 'xlsx';

export interface ReportMetadata {
  companyName: string;
  logoUrl?: string;
  address?: string;
  contactNumber?: string;
  email?: string;
  reportTitle: string;
  subtitle?: string;
  dateRange: string;
  houseFilter?: string;
  generatedBy: string;
  generatedAt: string;
}

export interface SheetData {
  sheetName: string;
  title: string;
  columns: { header: string; key: string; width?: number }[];
  data: Record<string, any>[];
  summaryRow?: Record<string, any>;
}

/**
 * Export tabular data to professional Excel (.xlsx) file with metadata headers,
 * formatted columns, and summary totals.
 */
export const exportReportToExcel = (
  metadata: ReportMetadata,
  sheets: SheetData[],
  filename: string
) => {
  const wb = XLSX.utils.book_new();

  sheets.forEach((sheet) => {
    // 1. Build the worksheet rows starting with Company Header
    const rows: any[][] = [];

    // Header block
    rows.push([metadata.companyName.toUpperCase()]);
    if (metadata.address) rows.push([`Address: ${metadata.address}`]);
    if (metadata.contactNumber || metadata.email) {
      rows.push([`Contact: ${metadata.contactNumber || 'N/A'} | Email: ${metadata.email || 'N/A'}`]);
    }
    rows.push([]); // empty row
    rows.push([sheet.title.toUpperCase()]);
    rows.push([`Report Period: ${metadata.dateRange} | Scope: ${metadata.houseFilter || 'All Houses'}`]);
    rows.push([`Generated By: ${metadata.generatedBy} on ${metadata.generatedAt}`]);
    rows.push([]); // empty row

    // Table Header Row
    const headerRow = sheet.columns.map((c) => c.header);
    rows.push(headerRow);

    // Data Rows
    sheet.data.forEach((item) => {
      const row = sheet.columns.map((c) => {
        const val = item[c.key];
        if (val === undefined || val === null) return '';
        if (typeof val === 'number') {
          return Number.isInteger(val) ? val : Number(val.toFixed(2));
        }
        return val;
      });
      rows.push(row);
    });

    // Summary / Totals Row
    if (sheet.summaryRow) {
      rows.push([]); // separation
      const summaryValues = sheet.columns.map((c, idx) => {
        if (idx === 0 && !sheet.summaryRow![c.key]) return 'TOTAL / SUMMARY';
        const val = sheet.summaryRow![c.key];
        if (val === undefined || val === null) return '';
        if (typeof val === 'number') {
          return Number.isInteger(val) ? val : Number(val.toFixed(2));
        }
        return val;
      });
      rows.push(summaryValues);
    }

    // Signatures
    rows.push([]);
    rows.push([]);
    rows.push(['PREPARED BY:', '', 'VERIFIED BY:', '', 'APPROVED BY:']);
    rows.push([metadata.generatedBy, '', 'Farm Veterinarian / Supervisor', '', 'Operations Manager']);

    // Create Worksheet
    const ws = XLSX.utils.aoa_to_sheet(rows);

    // Auto-fit column widths
    const colWidths = sheet.columns.map((c, colIndex) => {
      let maxLen = Math.max(c.header.length, c.width || 12);
      sheet.data.forEach((row) => {
        const val = String(row[c.key] ?? '');
        if (val.length > maxLen) maxLen = Math.min(val.length, 45);
      });
      return { wch: maxLen + 3 };
    });

    // Assign width to first column if title is long
    if (colWidths.length > 0 && colWidths[0].wch < 20) {
      colWidths[0].wch = 20;
    }
    ws['!cols'] = colWidths;

    // Add worksheet to workbook
    XLSX.utils.book_append_sheet(wb, ws, sheet.sheetName.substring(0, 31));
  });

  // Write file
  const sanitizedFilename = filename.endsWith('.xlsx') ? filename : `${filename}.xlsx`;
  XLSX.writeFile(wb, sanitizedFilename);
};

/**
 * Export lightweight CSV
 */
export const exportReportToCsv = (
  filename: string,
  columns: { header: string; key: string }[],
  data: Record<string, any>[]
) => {
  const headerLine = columns.map((c) => `"${c.header.replace(/"/g, '""')}"`).join(',');
  const rowLines = data.map((item) =>
    columns
      .map((c) => {
        const val = item[c.key] ?? '';
        return `"${String(val).replace(/"/g, '""')}"`;
      })
      .join(',')
  );

  const csvContent = [headerLine, ...rowLines].join('\r\n');
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.setAttribute('href', url);
  link.setAttribute('download', filename.endsWith('.csv') ? filename : `${filename}.csv`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
};
