import * as XLSX from 'xlsx';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export interface ReportMetadata {
  companyName: string;
  logoUrl?: string;
  address?: string;
  contactNumber?: string;
  email?: string;
  reportTitle: string;
  subtitle?: string;
  dateRange: string;
  houseFilter?: string;
  generatedBy: string;
  generatedAt: string;
}

export interface SheetData {
  sheetName: string;
  title: string;
  columns: { header: string; key: string; width?: number; align?: 'left' | 'center' | 'right' }[];
  data: Record<string, any>[];
  summaryRow?: Record<string, any>;
}

export interface PdfExportOptions {
  orientation?: 'portrait' | 'landscape';
  unit?: 'pt' | 'mm' | 'cm' | 'in';
  format?: 'a4' | 'letter' | 'legal';
  headerColor?: [number, number, number]; // RGB
  accentColor?: [number, number, number];
}

/**
 * Export tabular data to professional PDF file with metadata headers,
 * company letterhead, formatted columns, summary totals, page numbers, and official signatures.
 */
export const exportReportToPdf = (
  metadata: ReportMetadata,
  sheets: SheetData[],
  filename: string,
  options: PdfExportOptions = {}
) => {
  const orientation = options.orientation || (sheets.some(s => s.columns.length > 7) ? 'landscape' : 'portrait');
  const doc = new jsPDF({
    orientation,
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 14;

  const primaryColor: [number, number, number] = options.headerColor || [19, 78, 74]; // Forest Dark Emerald #134e4a
  const slateDark: [number, number, number] = [30, 41, 59]; // #1e293b
  const slateMuted: [number, number, number] = [100, 116, 139]; // #64748b
  const bgBadgeColor: [number, number, number] = [240, 253, 250]; // #f0fdfa

  sheets.forEach((sheet, sheetIndex) => {
    if (sheetIndex > 0) {
      doc.addPage(undefined, orientation);
    }

    let currentY = margin;

    // 1. Company Letterhead Header
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    doc.setTextColor(...primaryColor);
    const companyTitle = (metadata.companyName || 'L.P. LIM CITY FAMILY FARM INC').toUpperCase();
    doc.text(companyTitle, margin, currentY + 2);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8.5);
    doc.setTextColor(...slateMuted);
    let contactLine = '';
    if (metadata.address) contactLine += metadata.address;
    if (metadata.contactNumber) contactLine += (contactLine ? ' | Tel: ' : 'Tel: ') + metadata.contactNumber;
    if (metadata.email) contactLine += (contactLine ? ' | Email: ' : 'Email: ') + metadata.email;
    
    if (contactLine) {
      doc.text(contactLine, margin, currentY + 7);
      currentY += 6;
    } else {
      currentY += 4;
    }

    // Top Divider Line
    doc.setDrawColor(203, 213, 225); // slate-300
    doc.setLineWidth(0.5);
    doc.line(margin, currentY + 5, pageWidth - margin, currentY + 5);
    currentY += 10;

    // 2. Report Title Banner Box
    doc.setFillColor(...bgBadgeColor);
    doc.setDrawColor(153, 246, 228); // mint-300
    doc.roundedRect(margin, currentY, pageWidth - (margin * 2), 14, 2, 2, 'FD');

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(...slateDark);
    doc.text(sheet.title || metadata.reportTitle, margin + 4, currentY + 5.5);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(...slateMuted);
    const metaDetails = `Period: ${metadata.dateRange}  |  Scope: ${metadata.houseFilter || 'All Houses'}  |  Generated by: ${metadata.generatedBy} (${metadata.generatedAt})`;
    doc.text(metaDetails, margin + 4, currentY + 10.5);

    currentY += 18;

    // 3. Prepare Table Headers and Body
    const head = [sheet.columns.map(c => c.header)];
    const body = sheet.data.map(row =>
      sheet.columns.map(c => {
        const val = row[c.key];
        if (val === undefined || val === null) return '-';
        if (typeof val === 'number') {
          return Number.isInteger(val) ? val.toLocaleString() : Number(val.toFixed(2)).toLocaleString();
        }
        return String(val);
      })
    );

    // Summary row
    let foot: string[][] | undefined = undefined;
    if (sheet.summaryRow) {
      const footRow = sheet.columns.map((c, idx) => {
        if (idx === 0 && !sheet.summaryRow![c.key]) return 'TOTAL / SUMMARY';
        const val = sheet.summaryRow![c.key];
        if (val === undefined || val === null) return '';
        if (typeof val === 'number') {
          return Number.isInteger(val) ? val.toLocaleString() : Number(val.toFixed(2)).toLocaleString();
        }
        return String(val);
      });
      foot = [footRow];
    }

    // Column alignments
    const columnStyles: Record<number, any> = {};
    sheet.columns.forEach((col, idx) => {
      const align = col.align || (col.header.includes('%') || col.header.includes('Total') || col.header.includes('Qty') || col.header.includes('Count') || col.header.includes('Egg') || col.header.includes('Wt') ? 'right' : 'left');
      columnStyles[idx] = { halign: align };
    });

    // 4. Render Table with autoTable
    autoTable(doc, {
      startY: currentY,
      margin: { left: margin, right: margin, bottom: 26 },
      head: head,
      body: body,
      foot: foot,
      theme: 'grid',
      styles: {
        font: 'helvetica',
        fontSize: 7.5,
        cellPadding: 2.2,
        textColor: [30, 41, 59],
        lineColor: [226, 232, 240],
        lineWidth: 0.15,
        overflow: 'linebreak',
      },
      headStyles: {
        fillColor: primaryColor,
        textColor: [255, 255, 255],
        fontStyle: 'bold',
        fontSize: 8,
        halign: 'center',
        valign: 'middle',
      },
      alternateRowStyles: {
        fillColor: [248, 250, 252],
      },
      footStyles: {
        fillColor: [241, 245, 249],
        textColor: [15, 23, 42],
        fontStyle: 'bold',
        fontSize: 8,
      },
      columnStyles,
      didDrawPage: (data) => {
        // Footer: Page Number & Watermark
        const str = `Page ${doc.getNumberOfPages()}  |  FarmFlow Pro Central Farm Management System  |  Confidential External Record`;
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(7.5);
        doc.setTextColor(148, 163, 184); // slate-400
        doc.text(str, pageWidth / 2, pageHeight - 8, { align: 'center' });
      }
    });

    // 5. Verification Signatures on the final page
    const finalY = (doc as any).lastAutoTable?.finalY || currentY + 50;
    if (finalY + 24 < pageHeight - 15) {
      const signY = finalY + 12;
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(7.5);
      doc.setTextColor(...slateDark);
      
      const sigColWidth = (pageWidth - (margin * 2)) / 3;

      // Sig 1
      doc.line(margin + 2, signY + 7, margin + sigColWidth - 10, signY + 7);
      doc.text('PREPARED BY (Field Staff / Encoder):', margin + 2, signY + 11);
      doc.setFont('helvetica', 'normal');
      doc.text(metadata.generatedBy || 'Authorized Operator', margin + 2, signY + 15);

      // Sig 2
      doc.setFont('helvetica', 'bold');
      doc.line(margin + sigColWidth + 2, signY + 7, margin + (sigColWidth * 2) - 10, signY + 7);
      doc.text('VERIFIED BY (Farm Supervisor / Leadman):', margin + sigColWidth + 2, signY + 11);
      doc.setFont('helvetica', 'normal');
      doc.text('Attending Veterinarian / Supervisor', margin + sigColWidth + 2, signY + 15);

      // Sig 3
      doc.setFont('helvetica', 'bold');
      doc.line(margin + (sigColWidth * 2) + 2, signY + 7, pageWidth - margin - 2, signY + 7);
      doc.text('APPROVED BY (Operations / Farm Manager):', margin + (sigColWidth * 2) + 2, signY + 11);
      doc.setFont('helvetica', 'normal');
      doc.text('Farm Operations Management', margin + (sigColWidth * 2) + 2, signY + 15);
    }
  });

  const sanitizedFilename = filename.endsWith('.pdf') ? filename : `${filename}.pdf`;
  doc.save(sanitizedFilename);
};

/**
 * Export tabular data to professional Excel (.xlsx) file with metadata headers,
 * formatted columns, and summary totals.
 */
export const exportReportToExcel = (
  metadata: ReportMetadata,
  sheets: SheetData[],
  filename: string
) => {
  const wb = XLSX.utils.book_new();

  sheets.forEach((sheet) => {
    const rows: any[][] = [];

    // Header block
    rows.push([metadata.companyName.toUpperCase()]);
    if (metadata.address) rows.push([`Address: ${metadata.address}`]);
    if (metadata.contactNumber || metadata.email) {
      rows.push([`Contact: ${metadata.contactNumber || 'N/A'} | Email: ${metadata.email || 'N/A'}`]);
    }
    rows.push([]); // empty row
    rows.push([sheet.title.toUpperCase()]);
    rows.push([`Report Period: ${metadata.dateRange} | Scope: ${metadata.houseFilter || 'All Houses'}`]);
    rows.push([`Generated By: ${metadata.generatedBy} on ${metadata.generatedAt}`]);
    rows.push([]); // empty row

    // Table Header Row
    const headerRow = sheet.columns.map((c) => c.header);
    rows.push(headerRow);

    // Data Rows
    sheet.data.forEach((item) => {
      const row = sheet.columns.map((c) => {
        const val = item[c.key];
        if (val === undefined || val === null) return '';
        if (typeof val === 'number') {
          return Number.isInteger(val) ? val : Number(val.toFixed(2));
        }
        return val;
      });
      rows.push(row);
    });

    // Summary / Totals Row
    if (sheet.summaryRow) {
      rows.push([]); // separation
      const summaryValues = sheet.columns.map((c, idx) => {
        if (idx === 0 && !sheet.summaryRow![c.key]) return 'TOTAL / SUMMARY';
        const val = sheet.summaryRow![c.key];
        if (val === undefined || val === null) return '';
        if (typeof val === 'number') {
          return Number.isInteger(val) ? val : Number(val.toFixed(2));
        }
        return val;
      });
      rows.push(summaryValues);
    }

    // Signatures
    rows.push([]);
    rows.push([]);
    rows.push(['PREPARED BY:', '', 'VERIFIED BY:', '', 'APPROVED BY:']);
    rows.push([metadata.generatedBy, '', 'Farm Veterinarian / Supervisor', '', 'Operations Manager']);

    // Create Worksheet
    const ws = XLSX.utils.aoa_to_sheet(rows);

    // Auto-fit column widths
    const colWidths = sheet.columns.map((c) => {
      let maxLen = Math.max(c.header.length, c.width || 12);
      sheet.data.forEach((row) => {
        const val = String(row[c.key] ?? '');
        if (val.length > maxLen) maxLen = Math.min(val.length, 45);
      });
      return { wch: maxLen + 3 };
    });

    if (colWidths.length > 0 && colWidths[0].wch < 20) {
      colWidths[0].wch = 20;
    }
    ws['!cols'] = colWidths;

    // Add worksheet to workbook
    XLSX.utils.book_append_sheet(wb, ws, sheet.sheetName.substring(0, 31));
  });

  const sanitizedFilename = filename.endsWith('.xlsx') ? filename : `${filename}.xlsx`;
  XLSX.writeFile(wb, sanitizedFilename);
};

/**
 * Export lightweight CSV with clean escaping, UTF-8 BOM, and formatted headers.
 */
export const exportReportToCsv = (
  filename: string,
  columns: { header: string; key: string }[],
  data: Record<string, any>[]
) => {
  const headerLine = columns.map((c) => `"${c.header.replace(/"/g, '""')}"`).join(',');
  const rowLines = data.map((item) =>
    columns
      .map((c) => {
        const val = item[c.key];
        if (val === undefined || val === null) return '""';
        if (typeof val === 'number') {
          return Number.isInteger(val) ? String(val) : String(Number(val.toFixed(2)));
        }
        return `"${String(val).replace(/"/g, '""')}"`;
      })
      .join(',')
  );

  // Add UTF-8 BOM for Microsoft Excel / CSV compatibility
  const csvContent = '\uFEFF' + [headerLine, ...rowLines].join('\r\n');
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.setAttribute('href', url);
  link.setAttribute('download', filename.endsWith('.csv') ? filename : `${filename}.csv`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
};
